version: "3"

services:
  # if you need build application:
  # app:
  #   image: image's link
  #   container_name: app
  #   ports:
  #     - 3000:3000
  #   restart: always
  server:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
